Bridge.assembly("TestGame2D", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","TestGame2D"];
    $m("TestGame2D.App", function () { return {"att":1048577,"a":2,"m":[{"a":2,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"App_OnUpdate","t":8,"sn":"App_OnUpdate","rt":$n[0].Void},{"a":2,"n":"GetMousePosition","t":8,"pi":[{"n":"c","pt":HTMLCanvasElement,"ps":0},{"n":"e","pt":Event,"ps":1}],"sn":"GetMousePosition","rt":$n[0].Void,"p":[HTMLCanvasElement,Event]},{"a":2,"n":"InitCanvas","t":8,"pi":[{"n":"width","pt":$n[0].Int32,"ps":0},{"n":"height","pt":$n[0].Int32,"ps":1},{"n":"color","dv":"#fff","o":true,"pt":$n[0].String,"ps":2}],"sn":"InitCanvas","rt":$n[0].Void,"p":[$n[0].Int32,$n[0].Int32,$n[0].String]},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void},{"a":2,"n":"Update","t":8,"sn":"Update","rt":$n[0].Void},{"a":2,"n":"HEIGHT","is":true,"t":4,"rt":$n[0].Int32,"sn":"HEIGHT","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"WIDTH","is":true,"t":4,"rt":$n[0].Int32,"sn":"WIDTH","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"canvas","is":true,"t":4,"rt":HTMLCanvasElement,"sn":"canvas"},{"a":1,"n":"ctx","is":true,"t":4,"rt":CanvasRenderingContext2D,"sn":"ctx"},{"a":2,"n":"player","t":4,"rt":$n[1].Player,"sn":"player"},{"a":2,"n":"OnUpdate","t":2,"ad":{"a":2,"n":"add_OnUpdate","t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"addOnUpdate","rt":$n[0].Void,"p":[Function]},"r":{"a":2,"n":"remove_OnUpdate","t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"removeOnUpdate","rt":$n[0].Void,"p":[Function]}}]}; }, $n);
    $m("TestGame2D.Character", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"SetDestination","t":8,"pi":[{"n":"x","pt":$n[0].Int32,"ps":0},{"n":"y","pt":$n[0].Int32,"ps":1}],"sn":"SetDestination","rt":$n[0].Void,"p":[$n[0].Int32,$n[0].Int32]},{"ov":true,"a":2,"n":"Update","t":8,"sn":"Update","rt":$n[0].Void},{"a":2,"n":"DestinationX","t":4,"rt":$n[0].Int32,"sn":"DestinationX","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"DestinationY","t":4,"rt":$n[0].Int32,"sn":"DestinationY","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"Speed","t":4,"rt":$n[0].Single,"sn":"Speed","box":function ($v) { return Bridge.box($v, System.Single, System.Single.format, System.Single.getHashCode);}}]}; }, $n);
    $m("TestGame2D.GameObject", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"v":true,"a":2,"n":"Draw","t":8,"pi":[{"n":"ctx","pt":CanvasRenderingContext2D,"ps":0}],"sn":"Draw","rt":$n[0].Void,"p":[CanvasRenderingContext2D]},{"v":true,"a":2,"n":"Init","t":8,"sn":"Init","rt":$n[0].Void},{"v":true,"a":2,"n":"Update","t":8,"sn":"Update","rt":$n[0].Void},{"a":2,"n":"PosX","t":4,"rt":$n[0].Int32,"sn":"PosX","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"PosY","t":4,"rt":$n[0].Int32,"sn":"PosY","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"imageElement","t":4,"rt":HTMLImageElement,"sn":"imageElement"}]}; }, $n);
    $m("TestGame2D.Player", function () { return {"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"}]}; }, $n);
});
